# PowerShell script to create .env.local file
# This will prompt you for each environment variable

Write-Host "🔧 Environment Setup for Manual Subscription Sync" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script will create a .env.local file with your environment variables." -ForegroundColor Yellow
Write-Host "You can find these values in:" -ForegroundColor Yellow
Write-Host "  - Supabase: Project Settings > API" -ForegroundColor Yellow
Write-Host "  - DodoPayments: Settings > API Keys" -ForegroundColor Yellow
Write-Host ""

# Check if .env.local already exists
if (Test-Path ".env.local") {
    Write-Host "⚠️  .env.local already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/n)"
    if ($overwrite -ne "y") {
        Write-Host "Exiting..." -ForegroundColor Red
        exit
    }
}

Write-Host ""
Write-Host "Please enter your environment variables:" -ForegroundColor Cyan
Write-Host ""

# Prompt for each variable
$SUPABASE_URL = Read-Host "NEXT_PUBLIC_SUPABASE_URL (e.g., https://xxxxx.supabase.co)"
$SUPABASE_ANON_KEY = Read-Host "NEXT_PUBLIC_SUPABASE_ANON_KEY"
$SUPABASE_SERVICE_KEY = Read-Host "SUPABASE_SERVICE_ROLE_KEY (⚠️  Keep this secret!)"
$DODO_API_KEY = Read-Host "DODO_PAYMENTS_API_KEY"

# Create .env.local file
$envContent = @"
# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_KEY

# DodoPayments Configuration
DODO_PAYMENTS_API_KEY=$DODO_API_KEY

# Generated by setup-env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

$envContent | Out-File -FilePath ".env.local" -Encoding UTF8

Write-Host ""
Write-Host "✅ .env.local file created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Run the sync script:" -ForegroundColor White
Write-Host "     npx tsx scripts/sync-subscription-by-customer.ts sasikumarkudimi@gmail.com" -ForegroundColor Gray
Write-Host ""
Write-Host "  2. Deploy to Vercel:" -ForegroundColor White
Write-Host "     git add ." -ForegroundColor Gray
Write-Host "     git commit -m 'Fix: Enhanced webhook logging'" -ForegroundColor Gray
Write-Host "     git push origin main" -ForegroundColor Gray
Write-Host ""
Write-Host "⚠️  Note: .env.local is in .gitignore and will not be committed" -ForegroundColor Yellow

